### ISSUE TITLE
Additional Board Support

### ISSUE THREAD

**Issue by McCallisterMicro** [ssilverman/TeensyDMX#14]
Would it be possible to add support for Adafruit's ATSAMD boards, like the Metro M0 and M4?

**Comment by ssilverman** [comment]
Thank you for the request. I don’t plan on working on support for other systems at this time. Partly because I don’t have the hardware, partly because of time constraints, and partly because I’m not as familiar with these environments. I’m open to discussing a contract or an offer of financial support for such a project, however.
